### PR TITLE
CI: Use GitHub Actions to build/validate/publish

### PR DESCRIPTION
**Pull request by sideshowbarker**
This change adds CI automation for building, validating and publishing the document using the https://github.com/w3c/spec-prod tooling.

### CODE REVIEW

**Comment by mikewest** [comment]
Thanks! Once we get it up in TR space, is it possible to wire things up to autopublish Working Drafts? If you can show me how to do that, I'm happy to set it up.

**Comment by sideshowbarker** [comment]
> Thanks! Once we get it up in TR space, is it possible to wire things up to autopublish Working Drafts? If you can show me how to do that, I'm happy to set it up.



Yeah, we can do that. The first step in getting it set up is for either you or Daniel to send a CfC to public-webappsec@w3.org, to ask the WG for a decision to use autopublishing. We can ask for a decision to cover all the WG’s deliverables. Here’s a draft:

---

This is CfC to record a Working Group decision to automate publication of WebAppSec deliverables to W3C “TR space”.

Details: To automate the publication of WebAppSec deliverables to `https://www.w3.org/TR/` URLs (so-called “TR space”), we have the opportunity to adopt the "Future Publication workflow" described in `https://www.w3.org/2014/08/pubworkflow.html`, using the “Echidna” tooling from `https://github.com/w3c/echidna`.

In essence, that workflow prevents the problem of documents in TR space becoming stale. It ensures that the versions in TR space get automatically updated each time an editor pushes/merges new commits to the GitHub repo for a document.

So we are now issuing this CfC to record a Working Group decision for moving to automated publication of all WebAppSec deliverables to their W3C TR-space URLs.

If you have comments about this CfC, please send them to this mailing list by March 17th. You’re not required to respond; silence will be considered agreement with the CfC — but you’re also welcome to send a statement of support if you want.

**Comment by mikewest** [comment]
https://lists.w3.org/Archives/Public/public-webappsec/2015Mar/0170.html <-- This is that CfC. :)

**Comment by sideshowbarker** [comment]
> [lists.w3.org/Archives/Public/public-webappsec/2015Mar/0170.html](https://lists.w3.org/Archives/Public/public-webappsec/2015Mar/0170.html) <-- This is that CfC. :)

ah cool — so then for the Post-Spectre Web Development docs, once we get it up in TR space, it’ll just be a matter of me getting the token that Echidna needs, and then either of us can edit the https://github.com/w3c/webappsec-post-spectre-webdev/blob/main/.github/workflows/build-validate-publish.yml file to add the Echidna bits, following the example at https://github.com/w3c/spec-prod/blob/main/docs/examples.md#deploy-to-w3c-using-echidna

And in the meantime, I can go ahead and do that for some other repos

**Pull request merged**
